name: Provider Pact Pipeline

on:
  push:
    paths:
      - 'sat-assesment2706/oms/**'
      - '.github/workflows/provider.yml'
  pull_request:
    paths:
      - 'sat-assesment2706/oms/**'
      - '.github/workflows/provider.yml'

jobs:
  provider-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Repository Structure
        run: |
          pwd
          ls -la
          find . -maxdepth 4 -type f -name "pom.xml"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Provider
        run: mvn -f sat-assesment2706/pom.xml -pl oms test

      - name: Can I Deploy
        if: success()
        run: >
          mvn -f sat-assesment2706/pom.xml
          -pl oms
          pact:can-i-deploy
          -Dpacticipant=oms
          -DpacticipantVersion=1.0-SNAPSHOT